config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resources :documents do
    resources :versions, only: %i[show update], module: :documents
    resources :changes, only: %i[show], module: :documents
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/document.rb
# frozen_string_literal: true

class Document < ApplicationRecord
  has_paper_trail
  has_many_attached :embeds

  before_save :set_embeds

  private

  def set_embeds
    return if content.blank?

    nokogiri_html = Nokogiri::HTML.parse(content)
    sgids = nokogiri_html.css('figure').map do |figure|
      trix_attachment = JSON.parse(figure['data-trix-attachment'])
      trix_attachment['sgid']
    end
    blobs = sgids.map { |sgid| ActiveStorage::Blob.find_signed(sgid) }

    self.embeds = blobs - embeds.map(&:blob)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/documents/changes_controller.rb
# frozen_string_literal: true

class Documents::ChangesController < ApplicationController
  def show
    @document = Document.find(params[:document_id])
    @version = @document.versions.find(params[:id])
  end
end

app/controllers/documents/versions_controller.rb
# frozen_string_literal: true

class Documents::VersionsController < ApplicationController
  def show
    @document = Document.find(params[:document_id])
    @version = @document.versions.find(params[:id])
  end

  def update
    @document = Document.find(params[:document_id])
    @version = @document.versions.find(params[:id])
    if @version.next.present?
      @document = @version.next.reify
      @document.save!
    end
    redirect_to document_path(@document)
  end
end

app/controllers/documents_controller.rb
class DocumentsController < ApplicationController
  before_action :set_document, only: [:show, :edit, :update, :destroy]

  # GET /documents
  # GET /documents.json
  def index
    @documents = Document.all
  end

  # GET /documents/1
  # GET /documents/1.json
  def show
  end

  # GET /documents/new
  def new
    @document = Document.new
  end

  # GET /documents/1/edit
  def edit
  end

  # POST /documents
  # POST /documents.json
  def create
    @document = Document.new(document_params)

    respond_to do |format|
      if @document.save
        format.html { redirect_to @document, notice: 'Document was successfully created.' }
        format.json { render :show, status: :created, location: @document }
      else
        format.html { render :new }
        format.json { render json: @document.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /documents/1
  # PATCH/PUT /documents/1.json
  def update
    respond_to do |format|
      if @document.update(document_params)
        format.html { redirect_to @document, notice: 'Document was successfully updated.' }
        format.json { render :show, status: :ok, location: @document }
      else
        format.html { render :edit }
        format.json { render json: @document.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /documents/1
  # DELETE /documents/1.json
  def destroy
    @document.destroy
    respond_to do |format|
      format.html { redirect_to documents_url, notice: 'Document was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_document
      @document = Document.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def document_params
      params.require(:document).permit(:name, :content)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/documents/_form.html.erb
<%= form_with(model: document, local: true) do |form| %>
  <% if document.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(document.errors.count, "error") %> prohibited this document from being saved:</h2>

      <ul>
        <% document.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.text_field :name, class: 'form-control', placeholder: '名称未設定' %>
  </div>

  <div class="form-group">
    <div data-controller="trix" data-direct-upload-url="<%= rails_direct_uploads_url %>" data-blob-url-template="<%= rails_service_blob_url(':signed_id', ':filename') %>">
      <%= form.hidden_field :content %>
      <trix-editor input="document_content" class="trix-content" data-action="trix-attachment-add->trix#attach"></trix-editor>
    </div>
  </div>

  <div class="actions">
    <%= form.submit class: 'btn btn-primary' %>
  </div>
<% end %>

app/views/documents/changes/show.html.erb
<div class="row justify-content-md-center">
  <div class="col-8 p-4">
    <div class="d-flex justify-content-between mb-3">
      <%= link_to "\"#{@document.name}\"へ戻る", document_path(@document) %>
    </div>
    <h1 class="font-weight-bold mb-4">
      差分を表示する
    </h1>
    <% @version.changeset.keys.select { |key| %w[name content].include?(key) }.each do |key| %>
      <div class="mb-4">
        <h3 class=font-weight-bold">
          <%= Document.human_attribute_name(key) %>
        </h3>
        <div>
          <%= raw Markdiff::Differ.new.render(*@version.changeset[key]) %>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/documents/edit.html.erb
<div class="row justify-content-md-center">
  <div class="col-8 p-4">
    <div class="d-flex justify-content-between mb-3">
      <%= link_to "\"#{@document.name}\"へ戻る", document_path(@document) %>
    </div>
    <%= render 'form', document: @document %>
  </div>
</div>

app/views/documents/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Documents</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Content</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @documents.each do |document| %>
      <tr>
        <td><%= document.name %></td>
        <td><%= document.content %></td>
        <td><%= link_to 'Show', document %></td>
        <td><%= link_to 'Edit', edit_document_path(document) %></td>
        <td><%= link_to 'Destroy', document, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Document', new_document_path %>

app/views/documents/new.html.erb
<div class="row justify-content-md-center">
  <div class="col-8 p-4">
    <div class="d-flex justify-content-between mb-3">
      <%= link_to 'ドキュメント一覧へ戻る', documents_path %>
    </div>
    <%= render 'form', document: @document %>
  </div>
</div>

app/views/documents/show.html.erb
<div class="row justify-content-md-center">
  <div class="col-8 p-4">
    <div class="d-flex justify-content-between mb-3">
      <%= link_to '編集', edit_document_path(@document), class: 'btn btn-outline-dark' %>
    </div>
    <h1 class="font-weight-bold mb-4">
      <%= @document.name %>
    </h1>

    <div>
      <%= simple_format(@document.content) %>
    </div>

    <hr>

    <div>
      <%= PaperTrail::Version.model_name.human %>
    </div>
    <ul>
      <% @document.versions.each do |version| %>
        <li class="mb-2">
          <div>
            <span>
              <%= version.created_at %>
            </span>
            <span>
              <%= t("events.#{version.event}", model: version.item.model_name.human) %>
            </span>
          </div>
          <div>
            <span>
              <%= link_to 'このバージョンを表示する', document_version_path(version.item, version) %>
            </span>
            <span>
              <%= link_to '差分を表示する', document_change_path(version.item, version) %>
            </span>
          </div>
        </li>
      <% end %>
    </ul>
  </div>
</div>

app/views/documents/versions/show.html.erb
<div class="row justify-content-md-center">
  <div class="col-8 p-4">
    <div class="d-flex justify-content-between mb-3">
      <%= link_to "\"#{@document.name}\"へ戻る", document_path(@document), class: 'align-self-center' %>
      <% if @version.next.present? %>
        <%= button_to 'このバージョンへ戻す', document_version_path(@document, @version),
          class: 'btn btn-outline-primary',
          method: :patch,
          data: { confirm: '本当によろしいですか？' } %>
      <% end %>
    </div>
    <h1 class="font-weight-bold mb-4">
      このバージョンを表示する
    </h1>
    <% @version.changeset.keys.select { |key| %w[name content].include?(key) }.each do |key| %>
      <div class="mb-4">
        <h3 class=font-weight-bold">
          <%= Document.human_attribute_name(key) %>
        </h3>
        <div>
          <%= raw @version.changeset[key].last %>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Writer</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application' %>
    <%= stylesheet_pack_tag 'application' %>
  </head>

  <body>
    <div class="container-fluid">
      <nav class="navbar navbar-expand-lg navbar-light bg-white shadow-sm fixed-top">
        <%= link_to t('application.brand'), documents_path, class: 'navbar-brand' %>
      </nav>
      <div style="padding-top:56px;">
        <div class="container">
          <%= yield %>
        </div>
      </div>
    </div>
  </body>
</html>